### ISSUE TITLE
Reading Protrack data from the serial port?

### ISSUE THREAD

**Issue by epeli** [leg0/paralog-tools#4]
I was searching on how to read protrack data and found this:

https://github.com/leg0/paralog-tools/wiki/Pro-Track-data-format

I was wondering what baudrates did you use when dumping the data from the serial port? It seems that what ever I try I always get some garbage. Ie. never saw the `DATA TRACK VER. 1.05` header coming from the device.

**Comment by leg0** [comment]
If I remember correctly then it was 9600.

**Comment by epeli** [comment]
Weird. I tried one too. Well, maybe something else is off on my setup...

**Comment by leg0** [comment]
I remembered incorrectly. Just checked and it was 19200 instead of 9600. 8 data bits, no parity, 1 stop bit with RTS/CTS flow control.
